stages:
  - build
  # - deploy

image: docker:20.10.16

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TLS_CERTDIR: '/certs'
  IMAGE_VERSION: v1
  ALIYUN_ACR_USERNAME: 'hanqiang@zjlab_life_science'
  ALIYUN_ACR_IMAGES_REGISTRY: 'mixbio-images-registry-1-registry.cn-hangzhou.cr.aliyuncs.com'
  # DOCKER_REGISTRY_MIRROR: 'https://qdyhe98e.mirror.aliyuncs.com'
  # DOCKER_CLIENT_TIMEOUT: 300
  # DOCKER_TIMEOUT: 300

services:
  - docker:20.10.16-dind
  # command: ['--registry-mirror', $DOCKER_REGISTRY_MIRROR]

before_script:
  - docker login -u $ALIYUN_ACR_USERNAME $ALIYUN_ACR_IMAGES_REGISTRY -p $ALIYUN_ACR_ACCESS_KEY

build_and_push:
  stage: build
  script:
    - docker build -t $ALIYUN_ACR_IMAGES_REGISTRY/ops/zjbrainscience-front:$IMAGE_VERSION .
    - docker push $ALIYUN_ACR_IMAGES_REGISTRY/ops/zjbrainscience-front:$IMAGE_VERSION
# deploy_beta:
#   stage: deploy
#   image: ${ACR_REGISTRY}/ops/dtzar/helm-kubectl:3.4.1-envsubst
#   script:
#     - set -x
#     - echo "$K8S_KUBECONFIG" > /root/.kube/config
# - helm repo add zb_hangzhou https://helm-chats-1.oss-cn-hangzhou.aliyuncs.com
# - kubectl config use-context $K8S_TEST_CONTEXT
# - envsubst < helm_value.yaml
# - envsubst < helm_value.yaml | helm upgrade -i -f - $RELEASE_NAME zb_hangzhou/general-frontend --set-file nginx.config=./nginx_default.conf -n ${KUBE_NAMESPACE}
