export default {
  "Action.Execution": "The state or process of overtly moving",
  "Action.Execution.Speech": "The state or process of overtly speaking",
  "Action.Imagination": "The state or process of imagining an overt movement of the body",
  "Action.Inhibition": "The state or process of inhibiting an overt movement of the body",
  "Action.Motor Learning": "Action.Motor Learning",
  "Action.Observation": "The state or process of observing an overt movement of the body",
  "Action.Preparation": "The state or process of preparing for an overt movement of the body",
  "Cognition": "The mental process of knowing, including the integration of awareness, perception, reasoning, and judgment",
  "Cognition.Attention": "The act or state of attending by applying the mind to any object of sense or thought",
  "Cognition.Language": "The mental faculty associated with knowledge of a system of objects or symbols, such as sounds or character sequences, that can be combined in various ways following a set of rules, especially to communicate thoughts, feelings, or instructions",
  "Cognition.Language.Orthography": "The mental faculty associated with the part of language study concerned with letters and spelling",
  "Cognition.Language.Phonology": "The mental faculty associated with knowledge of the distribution and patterning of speech sounds in a language and of the tacit rules governing pronunciation",
  "Cognition.Language.Semantics": "The mental faculty associated with knowledge of meaning in language forms",
  "Cognition.Language.Speech": "The mental faculty associated with knowledge of overtly or covertly speaking",
  "Cognition.Language.Syntax": "The mental faculty associated with knowledge of the rules for the formation of grammatical sentences in a language",
  "Cognition.Memory": "The mental faculty of retaining and reviving facts, events, or impressions, or of recalling or recognizing previous experiences",
  "Cognition.Memory.Explicit": "The memory that consists of information stored and retrieved explicitly from the external world. This information is about a specific event that has occurred at a specific time and place. Associations are done with previously related stimuli or experiences in the formation, storage and subsequent retrieval of these memories",
  "Cognition.Memory.Implicit": "The long-term memory of skills and procedures; is often not easily verbalized, but can be used without consciously thinking about it",
  "Cognition.Memory.Working": "The memory for intermediate results that must be held during thinking",
  "Cognition.Music": "The mental faculty associated with the art of sound in time that expresses ideas and emotions in significant forms through the elements of rhythm, melody, harmony, and color",
  "Cognition.Reasoning": "The mental faculty of forming conclusions, judgments, or inferences from facts or premises",
  "Cognition.Social Cognition": "The mental faculty associated with how people process social information, especially its encoding, storage, retrieval, and application to social situations",
  "Cognition.Somatic": "The mental faculty associated with knowledge of one's body",
  "Cognition.Spatial": "The mental faculty associated with awareness of the three-dimensional expanse in which all material objects are located and all events occur",
  "Cognition.Temporal": "The mental faculty associated with the system of sequential relations that any event has to any other as past, present, or future",
  "Emotion": "The mental faculty of experiencing an affective state of consciousness such as joy, sorrow, fear, hate, etc",
  "Emotion.Intensity": "How strong or intense an emotional stimulus is",
  "Emotion.Negative": "The experience of negative emotion; subsumes a variety of emotions including anger, contempt, disgust, guilt, fear, anxiety, hate, etc",
  "Emotion.Negative.Anger": "An emotion of wrath or ire characterized by displeasure and belligerence aroused by a wrong",
  "Emotion.Negative.Anxiety": "An emotion characterized by distress or uneasiness of mind caused by fear of danger or misfortune",
  "Emotion.Negative.Disgust": "An emotion characterized by a strong distaste, nausea, or loathing",
  "Emotion.Negative.Embarrassment": "An emotion charcterized by embarassment, disconcertment, or abashment",
  "Emotion.Negative.Fear": "An emotion of being afraid aroused by distress, impending danger, evil, pain, etc",
  "Emotion.Negative.Guilt": "A feeling of responsibility or remorse for some offense, crime, wrong, etc., whether real or imagined",
  "Emotion.Negative.Punishment/Loss": "The state of being deprived of or of being without something that one has had; a losing by defeat; failure to win or a penalty inflicted for an offense, fault, etc",
  "Emotion.Negative.Sadness": "An emotion of sorrow or mourning characterized by unhappiness or grief",
  "Emotion.Positive": "The experience of positive emotion; subsumes a variety of emotions including joy, happiness, contentment, love, etc",
  "Emotion.Positive.Happiness": "An emotion of well-being ranging from contentment to intense joy (excluding humor)",
  "Emotion.Positive.Humor": "An emotion of characterized by a comic, absurd, or incongruous quality causing amusement",
  "Emotion.Positive.Reward/Gain": "Something given or received in return or recompense for service, merit, hardship, etc, or to get (something desired), especially as a result of one's efforts; to acquire as an increase or addition or as profit",
  "Emotion.Valence": "The intrinsic attractiveness/'good'-ness (positive valence) or averseness/'bad'-ness (negative valence) of an event, object, or situation",
  "Interoception": "The mental faculty associated with sensitivity to stimuli originating inside of the body",
  "Interoception.Baroregulation": "The need to regulate blood pressure",
  "Interoception.Gastrointestinal/Genitourinary (GI/GU)": "Awareness of pressure or distension in gastrointestinal or genitourinary systems, including the mouth, esophagus, stomach, bladder, anus, rectum",
  "Interoception.Heartbeat Detection": "Awareness of one's heartbeat or a sensitivity of accurately detecting its pace or speed",
  "Interoception.Hunger": "The need for food",
  "Interoception.Osmoregulation": "The need for the body's cells to maintain fluid and electrolyte balance with their surroundings",
  "Interoception.Respiration Regulation": "The need for respiration",
  "Interoception.Sexuality": "The need for sexual activity",
  "Interoception.Sleep": "The need for the natural suspension, complete or partial, of consciousness",
  "Interoception.Thermoregulation": "The need for the maintenance of a constant internal body temperature independent of the environmental temperature",
  "Interoception.Thirst": "The need for liquid that causes a sensation of dryness in the mouth and throat",
  "Interoception.Vestibular": "Awareness of pressure or fullness within the ear",
  "Perception": "The mental faculty of apprehending knowledge by means of the senses",
  "Perception.Audition": "The sense of hearing",
  "Perception.Gustation": "The sense of tasting",
  "Perception.Olfaction": "The sense of smelling",
  "Perception.Somesthesis, All Subdomains": "The sensory systems associated with the skin, including touch, pressure, temperature and position",
  "Perception.Somesthesis.Pain": "The senses of bodily perception associated with an unpleasant sensation occurring in varying degrees of severity as a consequence of injury, disease, or emotional disorder",
  "Perception.Vision, All Subdomains": "The sense of sight",
  "Perception.Vision.Color": "The visual perception of the quality of an object or substance with respect to light reflected by the object, usually determined visually by measurement of hue, saturation, and brightness of the reflected light",
  "Perception.Vision.Motion": "The visual perception of the action or process of moving or of changing place or position",
  "Perception.Vision.Shape": "The visual perception of the quality of a distinct object in having an external surface or outline of specific form or figure"
}