export const atlasState = {
  "dimensions": {
    "x": [
      0.0003,
      "m"
    ],
    "y": [
      0.0003,
      "m"
    ],
    "z": [
      0.0003,
      "m"
    ]
  },
  "position": [
    97, 130, 86
  ],
  "crossSectionBackgroundAlpha": 0.3,
  "crossSectionScale": 0.85,
  "projectionOrientation": [
    -0.5143676400184631,
    0.5209823846817017,
    -0.4737120568752289,
    0.48948967456817627
  ],
  "projectionScale": 300,
  "sliceViewCoordinate": "anatomy",
  layout: "3sliceR"
}
export const categories = [
  {
      "name":"FP"
  },
  {
      "name":"SFG"
  },
  {
      "name":"IFG"
  },
  {
      "name":"OrG"
  },
  {
      "name":"M1"
  },
  {
      "name":"PM"
  },
  {
      "name":"PoCG"
  },
  {
      "name":"FPO"
  },
  {
      "name":"SPL"
  },
  {
      "name":"IPL"
  },
  {
      "name":"PrCu"
  },
  {
      "name":"PRL"
  },
  {
      "name":"STG"
  },
  {
      "name":"ITG"
  },
  {
      "name":"PHG"
  },
  {
      "name":"TP"
  },
  {
      "name":"V1"
  },
  {
      "name":"V2"
  },
  {
      "name":"VMO"
  },
  {
      "name":"INS"
  },
  {
      "name":"CG"
  },
  {
      "name":"Acb"
  },
  {
      "name":"Amyg"
  },
  {
      "name":"Cd"
  },
  {
      "name":"HF"
  },
  {
      "name":"Hy"
  },
  {
      "name":"GP"
  },
  {
      "name":"Pu"
  },
  {
      "name":"Tha"
  }
]

export const nodes = [
    {
        "id":0,
        "name":"FP.d",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":0.0
    },
    {
        "id":1,
        "name":"FP.m",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":0.0
    },
    {
        "id":2,
        "name":"FP.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":0.0
    },
    {
        "id":3,
        "name":"SFG.rm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":1.0
    },
    {
        "id":4,
        "name":"SFG.cm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":1.0
    },
    {
        "id":5,
        "name":"SFG.r",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":1.0
    },
    {
        "id":6,
        "name":"SFG.ri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":1.0
    },
    {
        "id":7,
        "name":"SFG.ci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":1.0
    },
    {
        "id":8,
        "name":"SFG.c",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":1.0
    },
    {
        "id":9,
        "name":"IFG.rd",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":2.0
    },
    {
        "id":10,
        "name":"IFG.cd",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":2.0
    },
    {
        "id":11,
        "name":"IFG.cv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":2.0
    },
    {
        "id":12,
        "name":"IFG.iv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":2.0
    },
    {
        "id":13,
        "name":"IFG.rv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":2.0
    },
    {
        "id":14,
        "name":"OrG.rm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":3.0
    },
    {
        "id":15,
        "name":"OrG.cm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":3.0
    },
    {
        "id":16,
        "name":"OrG.ri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":3.0
    },
    {
        "id":17,
        "name":"OrG.ci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":3.0
    },
    {
        "id":18,
        "name":"OrG.rl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":3.0
    },
    {
        "id":19,
        "name":"OrG.cl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":3.0
    },
    {
        "id":20,
        "name":"M1.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":4.0
    },
    {
        "id":21,
        "name":"M1.i",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":4.0
    },
    {
        "id":22,
        "name":"M1.d",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":4.0
    },
    {
        "id":23,
        "name":"M1.m",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":4.0
    },
    {
        "id":24,
        "name":"PM.rd",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":5.0
    },
    {
        "id":25,
        "name":"PM.cd",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":5.0
    },
    {
        "id":26,
        "name":"PM.i",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":5.0
    },
    {
        "id":27,
        "name":"PM.cv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":5.0
    },
    {
        "id":28,
        "name":"PM.rv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":5.0
    },
    {
        "id":29,
        "name":"PM.rm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":5.0
    },
    {
        "id":30,
        "name":"PM.cm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":5.0
    },
    {
        "id":31,
        "name":"PoCG.dm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":6.0
    },
    {
        "id":32,
        "name":"PoCG.d",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":6.0
    },
    {
        "id":33,
        "name":"PoCG.i",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":6.0
    },
    {
        "id":34,
        "name":"PoCG.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":6.0
    },
    {
        "id":35,
        "name":"FPOr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":7.0
    },
    {
        "id":36,
        "name":"FPOri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":7.0
    },
    {
        "id":37,
        "name":"FPOci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":7.0
    },
    {
        "id":38,
        "name":"FPOc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":7.0
    },
    {
        "id":39,
        "name":"SPL.rv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":8.0
    },
    {
        "id":40,
        "name":"SPL.iv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":8.0
    },
    {
        "id":41,
        "name":"SPL.cv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":8.0
    },
    {
        "id":42,
        "name":"SPL.rd",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":8.0
    },
    {
        "id":43,
        "name":"SPL.cd",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":8.0
    },
    {
        "id":44,
        "name":"SPL.m",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":8.0
    },
    {
        "id":45,
        "name":"IPL.sr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":46,
        "name":"IPL.sri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":47,
        "name":"IPL.sci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":48,
        "name":"IPL.sc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":49,
        "name":"IPL.gr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":50,
        "name":"IPL.gri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":51,
        "name":"IPL.gci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":52,
        "name":"IPL.gc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":9.0
    },
    {
        "id":53,
        "name":"PrCu.vr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":10.0
    },
    {
        "id":54,
        "name":"PrCu.dr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":10.0
    },
    {
        "id":55,
        "name":"PrCu.dc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":10.0
    },
    {
        "id":56,
        "name":"PrCu.di",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":10.0
    },
    {
        "id":57,
        "name":"PrCu.vi",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":10.0
    },
    {
        "id":58,
        "name":"PrCu.vc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":10.0
    },
    {
        "id":59,
        "name":"PrL.d",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":11.0
    },
    {
        "id":60,
        "name":"PrL.i",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":11.0
    },
    {
        "id":61,
        "name":"PrL.STS",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":11.0
    },
    {
        "id":62,
        "name":"PrL.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":11.0
    },
    {
        "id":63,
        "name":"SFL.r",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":64,
        "name":"SFL.i",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":65,
        "name":"STG.gc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":66,
        "name":"STG.gr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":67,
        "name":"STG.gri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":68,
        "name":"STG.gci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":69,
        "name":"STSU.rEx",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":70,
        "name":"STSU.cEx",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":71,
        "name":"STSU.r",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":72,
        "name":"STSU.ri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":73,
        "name":"STSU.ci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":74,
        "name":"STSU.c",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":12.0
    },
    {
        "id":75,
        "name":"STSL.r",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":13.0
    },
    {
        "id":76,
        "name":"STSL.cIn",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":13.0
    },
    {
        "id":77,
        "name":"STSL.cEx",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":13.0
    },
    {
        "id":78,
        "name":"ITG.gr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":13.0
    },
    {
        "id":79,
        "name":"ITG.gdc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":13.0
    },
    {
        "id":80,
        "name":"ITG.gvc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":13.0
    },
    {
        "id":81,
        "name":"PHG.r",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":14.0
    },
    {
        "id":82,
        "name":"PHG.mi",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":14.0
    },
    {
        "id":83,
        "name":"PHG.li",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":14.0
    },
    {
        "id":84,
        "name":"PHG.cm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":14.0
    },
    {
        "id":85,
        "name":"PHG.cl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":14.0
    },
    {
        "id":86,
        "name":"TP.vr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":15.0
    },
    {
        "id":87,
        "name":"TP.mr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":15.0
    },
    {
        "id":88,
        "name":"TP.lr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":15.0
    },
    {
        "id":89,
        "name":"TP.dr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":15.0
    },
    {
        "id":90,
        "name":"TP.cEx",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":15.0
    },
    {
        "id":91,
        "name":"TP.cIn",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":15.0
    },
    {
        "id":92,
        "name":"V1.cm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":16.0
    },
    {
        "id":93,
        "name":"V1.dl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":16.0
    },
    {
        "id":94,
        "name":"V1.vl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":16.0
    },
    {
        "id":95,
        "name":"V1.mvi",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":16.0
    },
    {
        "id":96,
        "name":"V1.mdi",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":16.0
    },
    {
        "id":97,
        "name":"V1.rm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":16.0
    },
    {
        "id":98,
        "name":"V2.l",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":17.0
    },
    {
        "id":99,
        "name":"V2.d",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":17.0
    },
    {
        "id":100,
        "name":"V2.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":17.0
    },
    {
        "id":101,
        "name":"V2.dm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":17.0
    },
    {
        "id":102,
        "name":"V2.vm",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":17.0
    },
    {
        "id":103,
        "name":"VMO.l",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":18.0
    },
    {
        "id":104,
        "name":"VMO.i",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":18.0
    },
    {
        "id":105,
        "name":"VMO.m",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":18.0
    },
    {
        "id":106,
        "name":"INS.vr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":19.0
    },
    {
        "id":107,
        "name":"INS.dr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":19.0
    },
    {
        "id":108,
        "name":"INS.ri",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":19.0
    },
    {
        "id":109,
        "name":"INS.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":19.0
    },
    {
        "id":110,
        "name":"INS.ci",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":19.0
    },
    {
        "id":111,
        "name":"INS.c",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":19.0
    },
    {
        "id":112,
        "name":"CG.vr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":113,
        "name":"CG.ir",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":114,
        "name":"CG.dr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":115,
        "name":"CG.idr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":116,
        "name":"CG.idc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":117,
        "name":"CG.ivr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":118,
        "name":"CG.ivc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":119,
        "name":"CG.dc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":120,
        "name":"CG.vc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":121,
        "name":"CG.RSr",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":122,
        "name":"CG.Rsi",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":123,
        "name":"CG.RSc",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":20.0
    },
    {
        "id":124,
        "name":"Acb.C",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":21.0
    },
    {
        "id":125,
        "name":"Acb.Sh",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":21.0
    },
    {
        "id":126,
        "name":"Amyg.cl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":22.0
    },
    {
        "id":127,
        "name":"Amyg.rl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":22.0
    },
    {
        "id":128,
        "name":"Amyg.m",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":22.0
    },
    {
        "id":129,
        "name":"Cd.Hv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":23.0
    },
    {
        "id":130,
        "name":"Cd.B",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":23.0
    },
    {
        "id":131,
        "name":"Cd.Hi",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":23.0
    },
    {
        "id":132,
        "name":"Cd.Hd",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":23.0
    },
    {
        "id":133,
        "name":"Cd.T",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":23.0
    },
    {
        "id":134,
        "name":"HF.c",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":24.0
    },
    {
        "id":135,
        "name":"HF.i",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":24.0
    },
    {
        "id":136,
        "name":"HF.r",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":24.0
    },
    {
        "id":137,
        "name":"Hy.cl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":25.0
    },
    {
        "id":138,
        "name":"Hy.rl",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":25.0
    },
    {
        "id":139,
        "name":"Hy.m",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":25.0
    },
    {
        "id":140,
        "name":"GP.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":26.0
    },
    {
        "id":141,
        "name":"GP.d",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":26.0
    },
    {
        "id":142,
        "name":"Pu.r",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":27.0
    },
    {
        "id":143,
        "name":"Pu.v",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":27.0
    },
    {
        "id":144,
        "name":"Pu.c",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":27.0
    },
    {
        "id":145,
        "name":"Tha.rv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":28.0
    },
    {
        "id":146,
        "name":"Tha.c",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":28.0
    },
    {
        "id":147,
        "name":"Tha.ld",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":28.0
    },
    {
        "id":148,
        "name":"Tha.l",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":28.0
    },
    {
        "id":149,
        "name":"Tha.m",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":28.0
    },
    {
        "id":150,
        "name":"Tha.Sh",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":28.0
    },
    {
        "id":151,
        "name":"Tha.cv",
        "value":3,
        "label":{
            "normal":{
                "show":true
            }
        },
        "category":28.0
    }
]